Repository TheAlgorithms/Go, pull requests merged in 2021-10, with the labels that each got.

#361 feat: generate parentheses
  strings/generateparentheses/generateparentheses.go
  strings/generateparentheses/generateparentheses_test.go
Labels: hacktoberfest-accepted, Reviewed

#364 Add error value to search and add related benchmark
  search/binary_test.go
  search/interpolation.go
  search/interpolation_test.go
  search/linear.go
  search/linear_test.go
  search/testcases.go
Labels: Reviewed

#363 Edit Distance Problem
  dynamic/editdistance.go
  dynamic/editdistance_test.go
Labels: hacktoberfest-accepted

#369 Adjust instructions in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Reviewed

#366 Math improvements
  math/max/bitwisemax.go
  math/max/bitwisemax_test.go
  math/moserdebruijnsequence/sequence.go
  math/pi/montecarlopi.go
Labels: Reviewed

#372 docs: fix invalid path to file
  README.md
Labels: Reviewed

#371 feat: reverse bits
  math/binary/reversebits.go
  math/binary/reversebits_test.go
Labels: Reviewed

#362 Added Straight Line Algorithms in the math directory.
  README.md
  math/geometry/straightlines.go
  math/geometry/straightlines_test.go
Labels: hacktoberfest-accepted, Reviewed
