Repository TheAlgorithms/Go, pull requests merged in 2022-10, with the labels that each got.

#559 feat(cipher/caesar): add fuzzy test to caesar cipher
  cipher/caesar/caesar.go
  cipher/caesar/caesar_test.go
Labels: hacktoberfest-accepted

#576 Updated Discord Invite Link
  CONTRIBUTING.md
  README.md
Labels: enhancement, invalid

#581 docs: convert issue templates to issue forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/new-optimize-implementation.md
  .github/ISSUE_TEMPLATE/new_implementation.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: enhancement
